### ISSUE TITLE
Criteria and extra info about coursework

### ISSUE THREAD

**Issue by ra91hw** [edrumm/F28WP-coursework#2]
![image](https://user-images.githubusercontent.com/55585832/67054737-69b0bc00-f13d-11e9-9e66-5c8815d9d6b9.png)

![image](https://user-images.githubusercontent.com/55585832/67054741-6d444300-f13d-11e9-9ead-88aa37bdd8da.png)

![image](https://user-images.githubusercontent.com/55585832/67054744-70d7ca00-f13d-11e9-85e1-2819fbe8c43f.png)

**Comment by cm210** [comment]
Regarding the cheating/security, testing and user interaction requirements, we could have a report page where players can report other players for cheating, report bugs or other problems.
